 //Se tienen que descargar la extensión "Rest Cliente" 
 //y después darle click a "Send Request" para provar los endpoints
 
###
//obtener todos los comics
GET http://localhost:3000/api/comics/todos HTTP/1.1


 //obtener un comic especifico
 GET http://localhost:3000/api/comics/3 HTTP/1.1

###

//crear un nuevo comic
POST http://localhost:3000/api/comics/ HTTP/1.1
Content-Type: application/json

{
    "nombre": "Wonder Woman",
    "añoDePublicacion" : 1940
}

###
//actulizar un comic
PUT http://localhost:3000/api/comics/4 HTTP/1.1
Content-Type: application/json

{
    "añoDePublicacion" : 1965
}
###
//obtener una lista de comics
GET http://localhost:3000/api/comics?cantidad=5&inicio=5 HTTP/1.1

##
//eliminar un comic
DELETE http://localhost:3000/api/comics/14 HTTP/1.1





